### ISSUE TITLE
Impossible to access to Pokématos map

### ISSUE THREAD

**Issue by ChicoRubio** [Ninadjeret/pokematos-app#159]
Bonjour,

J'espère trouver de l'aide par ici...
Depuis quelques semaines, je n'arrive plus à accéder à Pokématos par quelque moyen que ce soit. Lorsque je clique sur le lien de la map Pokématos (sur discord) ou que je tente d'y aller en la recherchant sur Google, j'ai toujours un message d'erreur et des lignes de codes qui s'affichent. J'ai tenté aussi sur mon ordi sans succès...

J'ai déconnecté mon compte discord et mis un autre pour accéder à la map, et là, pas de souci. Je suppose donc que le bug est entre mon compte discord (nécessaire pour se connecter à la map) et la map.

En pièce jointe, voici un screen de la page que j'ai lorsque je tente d'aller sur la map. (La page est bien plus longue que ça.)
![Screenshot_20200311-165517_Samsung Internet](https://user-images.githubusercontent.com/62069157/76437214-82a25e00-63b9-11ea-873c-9a5c19fce4e0.jpg)

En espérant que quelqu'un ait une solution voire le développeur.

Cordialement

**Comment by Ninadjeret** [comment]
L'API de Discord ne semble pas autoriser Pokématos à accéder à ton profil, pour une raison qui m'échappe pour l'instant. Investigation en cours
